config/routes.rb
BackboneRailsCrud::Application.routes.draw do

  resources :articles

  # Authentication
  devise_for :administrators

  # Admin namespace
  namespace :admin do
    resources :administrators, :only => [:index, :new, :create]
    resources :articles
  end
  match 'admin' => 'admin/home#index'

  root :to => 'home#index'

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :encryptable, :confirmable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :token_authenticatable, :lockable

  # Mass assignment protection
  attr_accessible :email, :password, :password_confirmation, :remember_me


  def as_json(options = {})
    super(options.merge(:except => [ :password, :encrypted_password ]))
  end
end

app/models/article.rb
class Article < ActiveRecord::Base

  # Mass assignment protection
  attr_accessible :title, :body

  # Validations
  validates :title, :presence => true, :uniqueness => { :case_sensitive => false }, :length => { :within => 3..64 }
  validates :body, :presence => true, :length => { :minimum => 20 }

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::HomeController
  respond_to :html, :json

  def index
    @articles = Article.all
    respond_with @articles
  end

  def show
    @article = Article.find params[:id]
    respond_with @article
  end

  def new
    @article = Article.new
    respond_with @article
  end

  def edit
    @article = Article.find params[:id]
  end

  def create
    @article = Article.new params[:article]
    flash[:notice] = 'Article was successfully created.' if @article.save
    respond_with :admin, @article
  end

  def update
    @article = Article.find params[:id]
    flash[:notice] = 'Article was successfully updated.' if @article.update_attributes(params[:article])
    respond_with :admin, @article
  end

  def destroy
    @article = Article.find params[:id]
    @article.destroy
    respond_with @article
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  layout 'admin'
  before_filter :authenticate_administrator!

  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class Api::HomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/index.html.haml
#admin

= content_for :javascript do
  :javascript
    jQuery(function() {
      new Admin({el: $("#admin")});
    });

app/views/admin/home/index.html.haml
%h1 Home

app/views/articles/_form.html.haml
= simple_form_for(@article) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h1 Listing articles

%table
  %tr
    %th
    %th
    %th

  - @articles.each do |article|
    %tr
      %td= link_to 'Show', article
      %td= link_to 'Edit', edit_article_path(article)
      %td= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Article', new_article_path

app/views/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_article_path(@article)
\|
= link_to 'Back', articles_path

app/views/home/index.html.haml
%h1 Nothing to see here

app/views/layouts/admin.html.haml
!!!
%html{ 'class' => 'no-js', :lang => 'en' }
  %head
    %title= "Backbone & Rails Admin"
    = stylesheet_link_tag 'admin'
    = javascript_include_tag 'admin'
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %ul.nav
            - if administrator_signed_in?
              %li{ :class => controller.controller_name == 'articles' ? 'active' : '' }= link_to 'Articles', admin_articles_path
              %li.divider-vertical
              %li{ :class => controller.controller_name == 'producers' ? 'active' : '' }= link_to 'Producers', admin_administrators_path
              %li= link_to 'Logout', destroy_administrator_session_path, :method => :delete
          .pull-right= link_to('Backbone & Rails Admin', admin_path, :class => 'brand')
    .container
      - if notice
        .alert.alert-block{ :'data-dismiss' => 'alert' }
          %a.close ×
          %p= notice
      .row
        - if content_for?(:sidebar)
          .span3
            .well
              %h2 Instructions
              = yield(:sidebar)
              %p &nbsp;
              %p &nbsp;
          .span9= yield
        - else
          .span12= yield
    #footer.container
      = link_to 'Copyleft', 'http://en.wikipedia.org/wiki/Copyleft'
      2012 Dave Rapin. Do whatever you like with this code.
    = yield :javascript

app/views/layouts/application.html.haml
!!!
%html{ 'class' => 'no-js', :lang => 'en' }
  %head
    %title= "Backbone & Rails"
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = yield

app/views/shared/_error_messages.html.haml
- if target.errors.any?
  .alert.alert-error.alert-block
    %a.close{ :'data-dismiss' => 'alert' } ×
    %h4.alert-heading
      = pluralize(target.errors.count, "error")
      prohibited this record from being saved:
    %br
    %ul
      - target.errors.full_messages.each do |msg|
        %li= msg